FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

RUN go install github.com/air-verse/air@latest
RUN go install github.com/a-h/templ/cmd/templ@latest

COPY go.mod go.sum .air.toml ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]