// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login(title string, acc_created string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>URL Shortener</h1><p class=\"text\">Just to see how the frontpage looks</p><br><h1>Login</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if acc_created != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>Your account was registered. You can sign in now</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <br><form id=\"form\" class=\"form\"><div class=\"form-group\"><label for=\"email\" class=\"form-label\">Email</label> <input class=\"form-input\" type=\"email\" name=\"email\" id=\"email\" required autocomplete=\"off\"><br><br><label for=\"password\" class=\"form-label\">Password</label> <input class=\"form-input\" type=\"password\" name=\"password\" id=\"password\" required autocomplete=\"off\"><br><br><button type=\"submit\" class=\"button-primary\">Submit</button></div></form><br><span>to <a href=\"http://localhost:8080/\"><span class=\"text-muted\">homepage</span></a></span><script>\n    url = \"http://localhost:8080/login\"\n    baseurl = \"http://localhost:8080\"\n\n    const form = document.querySelector(\"#form\")\n    const email = document.querySelector(\"#email\")\n    const password = document.querySelector(\"#password\")\n\n    async function post_login(e) {\n        e.preventDefault()\n        const formData = new FormData(form)\n\n        const body = {\n            email: formData.get(\"email\"),\n            password: formData.get(\"password\")\n        }\n        console.log(body)\n        try {\n            const response = await fetch(url, {\n                method: \"POST\",\n                headers: {\n                    \"Content-Type\": \"application/json\",\n                },\n                body: JSON.stringify(body)\n            })\n\n            if (!response.ok) {\n                throw new Error(`response status: ${response.status}`)\n            }\n\n            const result = await response.json();\n            window.location.href = baseurl + result\n            console.log(result)\n        }\n        catch {\n            console.error(error.message)\n        }\n    }\n    form.addEventListener(\"submit\", post_login)\n</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(title).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
